# Generated by Django 3.0.7 on 2020-06-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo_credits',
            field=models.CharField(default='unsplash.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='articles/'),
        ),
    ]
