# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_auto_20200624_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
