# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_article_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments',
        ),
    ]
