# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0009_auto_20200625_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='article',
            name='photo_credits',
            field=models.CharField(blank=True, default='unsplash.com', max_length=30),
        ),
    ]
