# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0010_auto_20200625_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo_credits',
            field=models.CharField(max_length=60),
        ),
    ]
