# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0012_auto_20200626_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='magazineApiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField()),
                ('editor', models.CharField(max_length=100)),
                ('taag', models.CharField(max_length=200)),
                ('article_imagee', models.CharField(max_length=200)),
                ('photo_credits', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MoringaMerch',
        ),
    ]
