# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 02:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0015_magazineapimodel_article_imagee'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineapimodel',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='magazineapimodel',
            name='article_imagee',
            field=models.ImageField(upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='magazineapimodel',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='magazineapimodel',
            name='photo_credits',
            field=models.CharField(blank=True, default='unsplash.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='magazineapimodel',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
        migrations.RemoveField(
            model_name='magazineapimodel',
            name='taag',
        ),
        migrations.AddField(
            model_name='magazineapimodel',
            name='taag',
            field=models.ManyToManyField(to='magazine.tags'),
        ),
    ]
