# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0016_auto_20200626_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazineapimodel',
            old_name='editor',
            new_name='editors',
        ),
        migrations.RenameField(
            model_name='magazineapimodel',
            old_name='photo_credits',
            new_name='photo_creditss',
        ),
        migrations.RenameField(
            model_name='magazineapimodel',
            old_name='post',
            new_name='posts',
        ),
        migrations.RenameField(
            model_name='magazineapimodel',
            old_name='pub_date',
            new_name='pub_dates',
        ),
        migrations.RenameField(
            model_name='magazineapimodel',
            old_name='taag',
            new_name='taags',
        ),
        migrations.RenameField(
            model_name='magazineapimodel',
            old_name='title',
            new_name='titles',
        ),
    ]
