# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0018_remove_magazineapimodel_editors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazineapimodel',
            old_name='titles',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='magazineapimodel',
            name='photo_creditss',
        ),
        migrations.RemoveField(
            model_name='magazineapimodel',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='magazineapimodel',
            name='pub_dates',
        ),
        migrations.RemoveField(
            model_name='magazineapimodel',
            name='taags',
        ),
        migrations.AddField(
            model_name='magazineapimodel',
            name='editor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='magazineapimodel',
            name='photo_credits',
            field=models.CharField(default='unsplash', max_length=100),
        ),
        migrations.AddField(
            model_name='magazineapimodel',
            name='post',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='magazineapimodel',
            name='taag',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='magazineapimodel',
            name='article_imagee',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
