# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0019_auto_20200626_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineapimodel',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='magazineapimodel',
            name='editor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='magazineapimodel',
            name='photo_credits',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='magazineapimodel',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='magazineapimodel',
            name='taag',
            field=models.CharField(max_length=200),
        ),
    ]
