# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0022_auto_20200626_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazineapimodel',
            name='taag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
