# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0024_auto_20200626_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='magazineapimodel',
            old_name='taag',
            new_name='tags',
        ),
    ]
