# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0025_auto_20200626_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
