# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0026_user_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_profile',
        ),
        migrations.AddField(
            model_name='editor',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='editor',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
