# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-27 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0030_auto_20200627_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='silly'),
        ),
    ]
