# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0033_auto_20200627_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, default='https://cdn.pixabay.com/photo/2017/08/30/01/05/milky-way-2695569__340.jpg', upload_to='articles/'),
        ),
    ]
