# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0034_auto_20200628_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='articles/'),
        ),
    ]
