# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0035_auto_20200628_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
