# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0037_remove_article_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='post',
        ),
    ]
