# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0038_auto_20200628_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='Article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
