# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0044_auto_20200628_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetterRecipients',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='magazine.Article'),
        ),
    ]
