# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-29 20:17
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0047_auto_20200629_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
