# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-30 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0048_auto_20200629_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
