# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-01 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0049_remove_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles'),
        ),
    ]
