# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-01 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0051_auto_20200701_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazineapimodel',
            old_name='pub_date',
            new_name='created_on',
        ),
    ]
