# Generated by Django 3.0 on 2020-07-01 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0053_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
