# Generated by Django 3.0 on 2020-07-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0054_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
