# Generated by Django 2.2.13 on 2020-07-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0057_auto_20200703_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazineapimodel',
            name='article_image',
            field=models.TextField(),
        ),
    ]
